In [ ]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame

import pandas as pd
import numpy as np
def create_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    df['總分'] = sum_values
    df['平均'] = sum_values / 5
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df
scores = np.random.randint(50, 101, size=(50, 5))
df = create_dataframe(scores)
df
#這是自行用ai生成的程式碼

科目     國文  英文  數學   自然  社會   總分    平均    排名
學生
學生1    97  73  59   65  54  348  69.6  40.0
學生2    79  79  87   62  64  371  74.2  30.0
學生3    60  66  91   60  98  375  75.0  29.0
學生4    74  95  63   82  70  384  76.8  22.0
學生5    58  89  54   60  62  323  64.6  48.0
學生6    86  57  94   56  89  382  76.4  25.0
學生7    60  51  75   53  94  333  66.6  43.0
學生8    50  65  83   57  91  346  69.2  41.0
學生9    53  81  81   51  63  329  65.8  46.0
學生10   94  62  93   91  97  437  87.4   3.0
學生11   67  58  82   99  78  384  76.8  22.0
學生12   52  54  93   85  82  366  73.2  33.0
學生13   91  56  60   55  94  356  71.2  38.0
學生14   54  83  91   76  78  382  76.4  25.0
學生15   90  89  80   79  78  416  83.2   7.0
學生16   86  88  96   54  85  409  81.8  11.0
學生17   91  83  81   95  88  438  87.6   2.0
學生18   61  67  87   56  60  331  66.2  45.0
學生19   56  71  68   77  55  327  65.4  47.0
學生20   51  75  67   93  79  365  73.0  34.0
學生21   93  88  75   65  93  414  82.8  10.0
學生22   88  83  64   73  79  387  77.4  19.0
學生23   94  52  89  100  81  416  83.2   7.0
學生24   92  93  54   65  65  369  73.8  31.0
學生25   79  53  72   75  81  360  72.0  36.0
學生26   98  74  74   53  68  367  73.4  32.0
學生27   91  77  99   68  52  387  77.4  19.0
學生28   98  80  97   88  61  424  84.8   6.0
學生29   93  71  70   71  87  392  78.4  16.0
學生30   68  59  50   50  94  321  64.2  49.0
學生31   93  82  75   50  89  389  77.8  18.0
學生32   97  70  85   87  88  427  85.4   5.0
學生33   82  57  84   87  91  401  80.2  13.0
學生34   85  91  72   97  57  402  80.4  12.0
學生35   96  56  75   87  67  381  76.2  28.0
學生36   64  66  57   87  89  363  72.6  35.0
學生37   76  69  74   97  68  384  76.8  22.0
學生38   67  87  62   62  81  359  71.8  37.0
學生39   87  87  92   52  97  415  83.0   9.0
學生40   51  69  81   73  80  354  70.8  39.0
學生41   50  79  86   82  95  392  78.4  16.0
學生42   80  91  93   53  69  386  77.2  21.0
學生43   74  54  53   77  62  320  64.0  50.0
學生44   82  64  86   91  59  382  76.4  25.0
學生45   92  64  57   69  61  343  68.6  42.0
學生46   96  93  56   66  87  398  79.6  15.0
學生47   66  57  68   55  86  332  66.4  44.0
學生48   88  65  70   92  86  401  80.2  13.0
學生49   82  67  88   93  98  428  85.6   4.0
學生50  100  98  95   94  54  441  88.2   1.0

In [3]:
import pandas as pd
import numpy as np
def create_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 11)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    df['總分'] = sum_values
    df['平均'] = sum_values / 5
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df
scores = np.random.randint(50, 101, size=(10, 5))
df = create_dataframe(scores)
df

科目     國文  英文  數學   自然   社會   總分    平均    排名
學生
學生1    95  59  67   62   64  347  69.4   8.0
學生2    96  68  52   91   51  358  71.6   6.0
學生3    70  50  96   56   56  328  65.6   9.0
學生4    69  53  52   53   70  297  59.4  10.0
學生5    64  73  54   57  100  348  69.6   7.0
學生6   100  97  67   90   77  431  86.2   1.0
學生7    56  98  93  100   78  425  85.0   2.0
學生8    54  88  59   95   88  384  76.8   4.0
學生9    66  73  77   77   87  380  76.0   5.0
學生10   67  72  72   85   96  392  78.4   3.0

In [ ]:
#這是分隔線

In [ ]:
#AI建立一個function
#資料來源:scores = np.random.randint(50,101,size=(50, 5))
#欄位: ['國文', '英文', '數學', '自然', '社會','總分','平均','排名']
#索引: ['學生' + str(i) for i in range(1, 51)]
#建立DataFrame
import numpy as np
import pandas as pd 

def build_scores_dataframe(scores):
    df = pd.DataFrame(scores,
                      columns=['國文', '英文', '數學', '自然', '社會'],
                      index=['學生' + str(i) for i in range(1, 51)])
    df.index.name = '學生'
    df.columns.name = '科目'
    sum_values = df.sum(axis=1)
    mean_values = df.mean(axis=1)
    df['總分'] = sum_values
    df['平均'] = mean_values
    rank_values = sum_values.rank(method='min', ascending=False)
    df['排名'] = rank_values
    return df

In [ ]:
scores = np.random.randint(50,101,size=(50, 5))
df = build_scores_dataframe(scores)
df
#AI建立一個function
#依據df
#建立1個統計的DataFrame
#欄位: ['國文', '英文', '數學', '自然', '社會']
#欄位: ['平均', '最高', '最低', '中間值']


df

In [ ]:
#建立1個統計的DataFrame
def create_statistics_dataframe(df):
    cols = ['國文', '英文', '數學', '自然', '社會']
    stats = df[cols].agg(['mean', 'max', 'min', 'median'])
    stats.index = ['平均', '最高', '最低', '中間值']
    return stats
create_statistics_dataframe(df)